language: python
python: "3.7.4"
install:
- pip install -q Django==$DJANGO_VERSION
script:
- python test/test.py
env:
- DJANGO_VERSION=2.2.3
deploy:
  provider: heroku
  api_key:
    secure: URIlL003y7OsBHUpt8b4wh6RGhuuw7h8rMORkNX+ZqXfaAr2tWC8BBlG46u3A2Bq1dqb5VwDf1VsHwozQtQN3dmxuuNNy+LehDMQGq1oCufAm26P9xMG0ASbSalFE9BG8+UtWvksQT4NGVHgVKLDQYaiyBZ00xbWmci/EqypxWUCNFxTwS9TKZxesV/qu1TlV/AXfT6LODHqYg/IaFWIwisHfDgHKLd3HQaLjMSrZby5Srza5fUq+WzRfHEKJdDTXg2ood5Nvy4gmCrwdxba8bhYHcST1ZOHE6MS1kUjI/HhmSIa33PU5eh+CvPGB38Rmk+T01NEkG1qY7al/ENbtnMF857C6wOf518xs/YHtG7PVLhAi5sPxrIt5N0VXGJi7CAxeIjhVOfdCF24JHV4rQBA7oOegs9ZqNqgtzC680tWfgrZGEGqpwdzCzuF97MpwpjNg1PrHL3h4khTmHwP/6KnuF/ZK82h6npI1+vQxQ/Iqm55UxrgvwQIXd+C6IDoqKr/MaJRn+c14EKA2qC5NkZsgcv9tliwbWKz4Ggy9tR7j1JCdAyG9xjwIb+y9yIwHLBY+o+BakT8kINh5OVt9qs+0ID2j8VefGW93GSScTGhNe/ehaazYHaqX5Mo1EvuzfxutYMHwU4Jp45opfV7ShIP5LaerRNYmhMdk+QgSe4=
  app: anjiaqi
