language: python
python: 3.7.4
install:
- pip install -r requirements.txt
- pip install -q Django==$DJANGO_VERSION
script:
- python manage.py test
env:
- DJANGO_VERSION=2.2.3
deploy:
  provider: heroku
  api_key:
    secure: J1XE5xG9N4WxIU4pr5dN4FRreZJ4R3IyBd4ZwjrfO7dYMYqHjMixHtXBO0KR6K+Xetrl965D2FLAkSQrUBkQSeTaZuaS2m4YKoRO3T06pyN0c1S/P0bHy5y7Mpo19T5H7x9rkngb/0pLgTLL0s/Sawj3Oq3CtNVADrkK6xgxLuMLSkvDFntqFaWR4+Pe2iVc4kvhthUPm2Mu/qEinrdxcAYHtBjyzc4DWHQj9Nru1nAoqd2IE46Yr2Cc22YMjp0UwodNQyxLoIqkDfQyD4VdWCt58IOZ8thpLkaEFMAFGl4qa5jEKdTAtbf6E8nJ8dfCQ73uHlfWpkxM8qbOT4wHYiynDIbe+RvuF7ZBLdrw+Crt5xQNIM7sNpNPMPr0wlwgQKuzfilH8ki52wGNomiikZriJie4ztTrp+sCQc0d/KQET7FocWP9xUq1obU125K8UMT+RDgK0PcXtDVkLne498/+WXG0lj4pIzuJjAZgVDlwprNDJtwTu5VQMTqBfaznYHjEZVH8WwOBhv4JbZ1XiBVYxjacNsIYuKzLyzDETNEXxKTkwEaJmljij3DU0J9EtPfRkrqNyYBuyTgADxVc2BpQ+xKVAPmJnKTI9YPBrLo1vhSzgXmEPhOqlyZlcqGM38DHuzuub+EbJaZERir1CgyCEU830vY4v40wss+1Z14=
  app: anjiaqi
  skip_cleanup: true
