language: python
python: 3.7.4
install:
- pip install -r requirements.txt
- pip install -q Django==$DJANGO_VERSION
script:
- python manage.py test
env:
- DJANGO_VERSION=2.2.3
deploy:
  provider: heroku
  api_key:
    secure: SXBlLF94RDL26hRj2SUNoabkY1qSPDzhLIphQuQXTKF2IYEKqiD5snVOuleK21c+DHqf2ceARAl2nofhuF2nwgTMT9Se/sd4fQFvhxSSCPIkv5lQqV9foqOWrn7q6j/7E3CVS4w5NEgM9WEJd5jaccdxx7CMp/CoqrNYwzuuZsVAKTTGXlQdloCXNALtycPzDrfcKN7L3pLZ2ziHzDExBn1VWqCPtc63gIoquF9cakk70XA+10AR6XwiBv9xvwBQx3x27SlNXy8K6IqKClDJx8nMeZLc0v7+CQeJBfnX9eKEGnxjcewjx+4QMjB0x/r6U0MDZVlnh1ehJfLsOJxOrUEwcxl931Fcp9fQwZDKJ5B1grxecGYh70/UZbb2pCS8SOhGVoBfl+gnW75xIeDV3kquxrehswNB7ifs2u4Jb0MiMpySbTHT63lkPN/cvP7pdCODas8nfhTQxlsZuor6igJ/J4JxJ67CtaLnA1SkOwC7aj0ADUF9eSqU30SS6rKkqkN4H7xAXUr/yAMrQSmNR4lJQHKMPs9PSF1ZwQ1iXXiljwjw6FRqm4HmHbMLa/TBIKFmy5Q6ivDiigpmLCdwuIftIuXgg/LdSUqFxA2o4nWeFz4Pg5z2SdJN1PO3KeAuoXElpw3N2V8gnrCuq9BxF30+m4z0It5KzjkGsnpigvQ=
  app: anjiaqi